// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/organization_users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of users for the given organization (requires organization_id filter) or a single user by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org-users"
                ],
                "summary": "List or get organization users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID filter (list lookup)",
                        "name": "filter[@exact:organization_id]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (max 500, default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.OrgUserListSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a pending org user and sends an activation email. No password on the wire.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org-users"
                ],
                "summary": "Create organization user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateOrgUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.CreateOrgUserSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/organization_users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of users for the given organization (requires organization_id filter) or a single user by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org-users"
                ],
                "summary": "List or get organization users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (single-user lookup)",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID filter (list lookup)",
                        "name": "filter[@exact:organization_id]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (max 500, default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.OrgUserListSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes the org user from the per-org DB and enqueues ACL cleanup.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org-users"
                ],
                "summary": "Delete organization user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.OrgUserSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially updates an org user. Username changes are rejected.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org-users"
                ],
                "summary": "Update organization user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.PatchOrgUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.OrgUserSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a pending admin user and sends an activation email. No password is accepted on the wire.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Create admin user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.CreateUserSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes an admin user. Cannot delete yourself or the last super-admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Delete admin user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.UserSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially updates an admin user. Username changes are rejected.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Update admin user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.UserSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        },
        "/applications/applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "POST creates a new application. GET returns one (by id) or a list (filtered by workspace_id). PATCH/PUT updates. DELETE soft-deletes (sets is_active=false).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Manage applications (CRUD)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID filter (list)",
                        "name": "workspace_id",
                        "in": "query"
                    },
                    {
                        "description": "Application body (POST/PATCH/PUT)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "POST creates a new application. GET returns one (by id) or a list (filtered by workspace_id). PATCH/PUT updates. DELETE soft-deletes (sets is_active=false).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Manage applications (CRUD)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID filter (list)",
                        "name": "workspace_id",
                        "in": "query"
                    },
                    {
                        "description": "Application body (POST/PATCH/PUT)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        },
        "/applications/applications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "POST creates a new application. GET returns one (by id) or a list (filtered by workspace_id). PATCH/PUT updates. DELETE soft-deletes (sets is_active=false).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Manage applications (CRUD)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID filter (list)",
                        "name": "workspace_id",
                        "in": "query"
                    },
                    {
                        "description": "Application body (POST/PATCH/PUT)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "POST creates a new application. GET returns one (by id) or a list (filtered by workspace_id). PATCH/PUT updates. DELETE soft-deletes (sets is_active=false).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Manage applications (CRUD)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID filter (list)",
                        "name": "workspace_id",
                        "in": "query"
                    },
                    {
                        "description": "Application body (POST/PATCH/PUT)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "POST creates a new application. GET returns one (by id) or a list (filtered by workspace_id). PATCH/PUT updates. DELETE soft-deletes (sets is_active=false).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Manage applications (CRUD)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID filter (list)",
                        "name": "workspace_id",
                        "in": "query"
                    },
                    {
                        "description": "Application body (POST/PATCH/PUT)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.ApplicationSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.ActivationEcho": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "entity.Application": {
            "type": "object",
            "properties": {
                "allow_password_login": {
                    "description": "AllowPasswordLogin toggles the username+password login endpoint\nfor this app. Default true preserves legacy behaviour; an admin\nflips it off to force the OAuth-only path. Both the login\nhandler and the public auth-methods endpoint honour this flag.",
                    "type": "boolean",
                    "default": true
                },
                "allow_recovery": {
                    "type": "boolean",
                    "default": true
                },
                "allow_registration": {
                    "type": "boolean",
                    "default": false
                },
                "client_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "default": true
                },
                "registration_type": {
                    "description": "RegistrationType declares how registration is collected:\n  - \"legacy\": consumers render a form with username + password\n    implicit and the admin-configured extras on top.\n  - \"oauth\":  provider delivers identity; extras only.\nOnly \"legacy\" is wired today; \"oauth\" is a declarative label\nwe surface so the consumer can branch its UI ahead of the\nprovider-flow implementation landing.",
                    "type": "string",
                    "default": "legacy"
                },
                "title": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "entity.ApplicationRequest": {
            "type": "object",
            "properties": {
                "allow_password_login": {
                    "type": "boolean"
                },
                "allow_recovery": {
                    "type": "boolean"
                },
                "allow_registration": {
                    "type": "boolean"
                },
                "client_id": {
                    "type": "string",
                    "example": "my-app"
                },
                "description": {
                    "type": "string",
                    "example": "App description"
                },
                "is_active": {
                    "type": "boolean"
                },
                "registration_type": {
                    "type": "string",
                    "example": "legacy"
                },
                "title": {
                    "type": "string",
                    "example": "My Application"
                },
                "workspace_id": {
                    "type": "string",
                    "example": "ws-uuid"
                }
            }
        },
        "entity.ApplicationSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/entity.Application"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "entity.CreateOrgUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "jdoe@example.com"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "organization_id": {
                    "type": "string",
                    "example": "org-uuid"
                },
                "redirect_application_id": {
                    "type": "string",
                    "example": "app-uuid"
                },
                "username": {
                    "type": "string",
                    "example": "jdoe"
                }
            }
        },
        "entity.CreateOrgUserResponse": {
            "type": "object",
            "properties": {
                "activation": {
                    "$ref": "#/definitions/entity.OrgActivationEcho"
                },
                "activation_error": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_a-digi_coco-iam_src_organizations_users_entity.User"
                }
            }
        },
        "entity.CreateOrgUserSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/entity.CreateOrgUserResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "entity.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "jdoe@example.com"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_super_admin": {
                    "type": "boolean",
                    "example": false
                },
                "username": {
                    "type": "string",
                    "example": "jdoe"
                }
            }
        },
        "entity.CreateUserResponse": {
            "type": "object",
            "properties": {
                "activation": {
                    "$ref": "#/definitions/entity.ActivationEcho"
                },
                "activation_error": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_a-digi_coco-iam_src_admin_users_entity.User"
                }
            }
        },
        "entity.CreateUserSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/entity.CreateUserResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "entity.OrgActivationEcho": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "entity.OrgUserListSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.OrgUserResponse"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "entity.OrgUserResponse": {
            "type": "object",
            "properties": {
                "activation_pending": {
                    "type": "boolean",
                    "example": false
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "default": true
                },
                "organization_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "entity.OrgUserSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/entity.OrgUserResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "entity.PatchOrgUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "new@example.com"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "entity.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "new@example.com"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_super_admin": {
                    "type": "boolean",
                    "example": false
                },
                "old_password": {
                    "type": "string",
                    "example": "OldPass1!"
                },
                "password": {
                    "type": "string",
                    "example": "NewPass1!"
                }
            }
        },
        "entity.UserSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/github_com_a-digi_coco-iam_src_admin_users_entity.User"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_a-digi_coco-iam_src_admin_users_entity.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "default": true
                },
                "is_super_admin": {
                    "type": "boolean",
                    "default": false
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_a-digi_coco-iam_src_organizations_users_entity.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "default": true
                },
                "organization_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.ErrorBody": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "resource not found"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer \u003cJWT token\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2026",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CoCo IAM API",
	Description:      "Multi-tenant Identity and Access Management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
