package swagger

import (
	_ "embed"
	"net/http"
	"strings"

	"github.com/a-digi/coco-server/server/request"
	"github.com/a-digi/coco-server/server/response"
	httpSwagger "github.com/swaggo/http-swagger"
)

// specJSON holds the OpenAPI spec embedded at compile time from static/swagger.json.
// The file is generated by `swag init` and copied to this directory by the Makefile
// swag-gen target, keeping the swag CLI tool out of the production binary.
//
//go:embed static/swagger.json
var specJSON []byte

// SpecHandler serves the Swagger UI at GET /api/v1/docs/
// It also handles /api/v1/docs (no trailing slash) by redirecting so that
// httpSwagger can compute the correct asset prefix from the URL.
type SpecHandler struct{}

func (h *SpecHandler) ServeHTTP(reqCtx request.RequestContext) {
	w := reqCtx.GetWriter()
	r := reqCtx.GetRequest()

	// httpSwagger derives its asset prefix from the URL path. If the path has
	// no trailing slash and no file extension it computes the wrong prefix,
	// causing a redirect to /api/v1/index.html instead of /api/v1/docs/index.html.
	// Forcing a redirect to the slash form fixes the prefix for all subsequent requests.
	if !strings.HasSuffix(r.URL.Path, "/") && !strings.Contains(r.URL.Path[strings.LastIndex(r.URL.Path, "/"):], ".") {
		http.Redirect(w, r, r.URL.Path+"/", http.StatusMovedPermanently)
		return
	}

	// HSTS/nosniff/Referrer-Policy only, deliberately not the shared
	// CSP default — swagger-ui-dist (embedded, no CDN calls) commonly
	// relies on inline styles/scripts, which a strict default-src
	// 'self' would break without verifying first. See
	// plan/todo/security/header-and-cache-poisoning.md.
	w.Header().Set("Strict-Transport-Security", "max-age=63072000; includeSubDomains")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Referrer-Policy", "strict-origin-when-cross-origin")

	httpSwagger.Handler(
		httpSwagger.URL("/api/v1/docs/openapi.json"),
	).ServeHTTP(w, r)
}

// RawSpecHandler serves the raw OpenAPI JSON spec at GET /api/v1/docs/openapi.json.
type RawSpecHandler struct{}

func (h *RawSpecHandler) ServeHTTP(reqCtx request.RequestContext) {
	w := reqCtx.GetWriter()
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Access-Control-Allow-Origin", "*")
	response.SetBaselineSecurityHeaders(w)
	w.WriteHeader(http.StatusOK)
	w.Write(specJSON)
}
