package swagger

import (
	_ "embed"
	"net/http"

	"github.com/a-digi/coco-server/server/request"
	httpSwagger "github.com/swaggo/http-swagger"
)

// specJSON holds the OpenAPI spec embedded at compile time from static/swagger.json.
// The file is generated by `swag init` and copied to this directory by the Makefile
// swag-gen target, keeping the swag CLI tool out of the production binary.
//
//go:embed static/swagger.json
var specJSON []byte

// SpecHandler serves the Swagger UI at GET /api/v1/docs/
type SpecHandler struct{}

func (h *SpecHandler) ServeHTTP(reqCtx request.RequestContext) {
	httpSwagger.Handler(
		httpSwagger.URL("/api/v1/docs/openapi.json"),
	).ServeHTTP(reqCtx.GetWriter(), reqCtx.GetRequest())
}

// RawSpecHandler serves the raw OpenAPI JSON spec at GET /api/v1/docs/openapi.json.
type RawSpecHandler struct{}

func (h *RawSpecHandler) ServeHTTP(reqCtx request.RequestContext) {
	w := reqCtx.GetWriter()
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.WriteHeader(http.StatusOK)
	w.Write(specJSON)
}
